### ISSUE TITLE
Maven not resolving webjars dependency

### ISSUE THREAD

**Issue by binhudakhalid** [donhenton/webjar-app#1]
> 

             <dependency>
            <groupId>com.dhenton9000.webjars</groupId>
            <artifactId>webjar-app</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

Missing artifact com.dhenton9000.webjars:webjar-app:jar:1.0-SNAPSHOT

**Comment by donhenton** [comment]
Sorry I didn't see this sooner. I'm guessing you are trying to use this elsewhere. I think this means you need to build *this* app locally (mvn clean install) which then should make it available for your consuming. Hope I'm understanding you correctly
